# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coverage"
  - "pip install coveralls"

# command to run tests, e.g. python setup.py test
script:
  "coverage run --source=python_algorithms setup.py test"

after_success:
  coveralls